name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build . --tag ghcr.io/kenramandha/cakdie_kasir:latest
          docker push ghcr.io/kenramandha/cakdie_kasir:latest

      - name: Deploy to Swarm
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Pull the latest image for this service
            docker pull ghcr.io/${{ github.repository }}:latest
            # Update the stack
            docker stack deploy -c ~/docker-compose.yml --with-registry-auth cakdie_kasir
